Return-Path: <alsa-devel-bounces@alsa-project.org>
X-Original-To: lists+alsa-devel@lfdr.de
Delivered-To: lists+alsa-devel@lfdr.de
Received: from alsa0.perex.cz (alsa0.perex.cz [77.48.224.243])
	by mail.lfdr.de (Postfix) with ESMTPS id E47306F8EFC
	for <lists+alsa-devel@lfdr.de>; Sat,  6 May 2023 07:58:59 +0200 (CEST)
Received: from alsa1.perex.cz (alsa1.perex.cz [207.180.221.201])
	(using TLSv1.2 with cipher ADH-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	by alsa0.perex.cz (Postfix) with ESMTPS id 3EBF32B33;
	Sat,  6 May 2023 07:58:09 +0200 (CEST)
DKIM-Filter: OpenDKIM Filter v2.11.0 alsa0.perex.cz 3EBF32B33
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=alsa-project.org;
	s=default; t=1683352739;
	bh=oovjI6jbdLa3skcz+AwUpdZypL6joV/hrW+m8eH0m2I=;
	h=Date:From:To:Subject:In-Reply-To:References:CC:List-Id:
	 List-Archive:List-Help:List-Owner:List-Post:List-Subscribe:
	 List-Unsubscribe:From;
	b=NFx8tT3bO2WP8O0yt9U5xEbnXeWE/CF1OjomNtU0snADFOdJKLRd5p6eqjj2DrsaQ
	 rBGqPGE5xbKb/QM62fydmHSN/oHH6VjAOTLg5MnVUkOG3fB1rbaJ97MtGBvETZoPkg
	 IYTj3Dj2uuhS7CtEWu3GsDnj30EXh6nPCYDtAwys=
Received: from mailman-core.alsa-project.org (mailman-core.alsa-project.org [10.254.200.10])
	by alsa1.perex.cz (Postfix) with ESMTP id 072F8F80534;
	Sat,  6 May 2023 07:57:55 +0200 (CEST)
Received: by alsa1.perex.cz (Postfix, from userid 50401)
	id CEC0EF8053B; Sat,  6 May 2023 07:57:51 +0200 (CEST)
X-Spam-Checker-Version: SpamAssassin 3.4.6 (2021-04-09) on alsa1.perex.cz
X-Spam-Level: 
X-Spam-Status: No, score=-5.2 required=5.0 tests=DKIM_SIGNED,DKIM_VALID,
	DKIM_VALID_AU,DKIM_VALID_EF,RCVD_IN_DNSWL_HI,SPF_HELO_NONE,SPF_PASS,
	T_SCC_BODY_TEXT_LINE,URIBL_BLOCKED shortcircuit=no autolearn=ham
	autolearn_force=no version=3.4.6
Received: from smtp-out2.suse.de (smtp-out2.suse.de
 [IPv6:2001:67c:2178:6::1d])
	(using TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)
	 key-exchange X25519 server-signature RSA-PSS (4096 bits) server-digest
 SHA256)
	(No client certificate requested)
	by alsa1.perex.cz (Postfix) with ESMTPS id F25EAF80533
	for <alsa-devel@alsa-project.org>; Sat,  6 May 2023 07:57:47 +0200 (CEST)
DKIM-Filter: OpenDKIM Filter v2.11.0 alsa1.perex.cz F25EAF80533
Authentication-Results: alsa1.perex.cz;
	dkim=pass (1024-bit key,
 unprotected) header.d=suse.de header.i=@suse.de header.a=rsa-sha256
 header.s=susede2_rsa header.b=DZ3ZONca;
	dkim=pass header.d=suse.de header.i=@suse.de header.a=ed25519-sha256
 header.s=susede2_ed25519 header.b=DBb0IShc
Received: from imap2.suse-dmz.suse.de (imap2.suse-dmz.suse.de
 [192.168.254.74])
	(using TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)
	 key-exchange X25519 server-signature ECDSA (P-521) server-digest SHA512)
	(No client certificate requested)
	by smtp-out2.suse.de (Postfix) with ESMTPS id F2EDA20B61;
	Sat,  6 May 2023 05:57:46 +0000 (UTC)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=suse.de;
 s=susede2_rsa;
	t=1683352667;
 h=from:from:reply-to:date:date:message-id:message-id:to:to:cc:cc:
	 mime-version:mime-version:content-type:content-type:
	 in-reply-to:in-reply-to:references:references;
	bh=9i0SeTx8lIGtrzyO+u8rvIkHwihnziAaxcN8UqkZhFc=;
	b=DZ3ZONcavrzajmpiiy4Xnow3NPEbLx5hDAbTEUaOKDf3dFrA2JdVXZrf5jfMgXeyqtZh2z
	tI5xXsRNbLwzHwDAFMv4wT6KX8fMBOJ3+5dAqZwlQrn6zLU3goriXrit6T8QPeI/V9JOps
	QGqoglH1TMNDsDQwFyy0WRSoelVp+oM=
DKIM-Signature: v=1; a=ed25519-sha256; c=relaxed/relaxed; d=suse.de;
	s=susede2_ed25519; t=1683352667;
	h=from:from:reply-to:date:date:message-id:message-id:to:to:cc:cc:
	 mime-version:mime-version:content-type:content-type:
	 in-reply-to:in-reply-to:references:references;
	bh=9i0SeTx8lIGtrzyO+u8rvIkHwihnziAaxcN8UqkZhFc=;
	b=DBb0IShcR56G7dP/+K75zwoycxASgT0YrHfurBTFVaxbbXEOMwLVIPBm1uPTTN1OSFOqAJ
	64pRhoFRCPA6yIDw==
Received: from imap2.suse-dmz.suse.de (imap2.suse-dmz.suse.de
 [192.168.254.74])
	(using TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)
	 key-exchange X25519 server-signature ECDSA (P-521) server-digest SHA512)
	(No client certificate requested)
	by imap2.suse-dmz.suse.de (Postfix) with ESMTPS id AB9D4134FB;
	Sat,  6 May 2023 05:57:46 +0000 (UTC)
Received: from dovecot-director2.suse.de ([192.168.254.65])
	by imap2.suse-dmz.suse.de with ESMTPSA
	id eP9hKFrsVWQAPgAAMHmgww
	(envelope-from <tiwai@suse.de>); Sat, 06 May 2023 05:57:46 +0000
Date: Sat, 06 May 2023 07:57:46 +0200
Message-ID: <87ttwqgfxh.wl-tiwai@suse.de>
From: Takashi Iwai <tiwai@suse.de>
To: Srinivas Kandagatla <srinivas.kandagatla@linaro.org>
Subject: Re: [PATCH 1/3] ALSA: pcm: add snd_pcm_add_chmap_ctls_with_prefix
In-Reply-To: <20230505165514.4666-2-srinivas.kandagatla@linaro.org>
References: <20230505165514.4666-1-srinivas.kandagatla@linaro.org>
	<20230505165514.4666-2-srinivas.kandagatla@linaro.org>
User-Agent: Wanderlust/2.15.9 (Almost Unreal) Emacs/27.2 Mule/6.0
MIME-Version: 1.0 (generated by SEMI-EPG 1.14.7 - "Harue")
Content-Type: text/plain; charset=US-ASCII
Message-ID-Hash: BE4NG5O64V6VFY7RRBQ2ZYZ5M7ILWYDM
X-Message-ID-Hash: BE4NG5O64V6VFY7RRBQ2ZYZ5M7ILWYDM
X-MailFrom: tiwai@suse.de
X-Mailman-Rule-Misses: dmarc-mitigation; no-senders; approved; emergency;
 loop; banned-address; member-moderation;
 header-match-alsa-devel.alsa-project.org-0;
 header-match-alsa-devel.alsa-project.org-1; nonmember-moderation;
 administrivia; implicit-dest; max-recipients; max-size; news-moderation;
 no-subject; digests; suspicious-header
CC: broonie@kernel.org, tiwai@suse.com, lgirdwood@gmail.com,
 ckeepax@opensource.cirrus.com, kuninori.morimoto.gx@renesas.com,
 linux-kernel@vger.kernel.org, pierre-louis.bossart@linux.intel.com,
 alsa-devel@alsa-project.org
X-Mailman-Version: 3.3.8
Precedence: list
List-Id: "Alsa-devel mailing list for ALSA developers -
 http://www.alsa-project.org" <alsa-devel.alsa-project.org>
Archived-At: 
 <https://mailman.alsa-project.org/hyperkitty/list/alsa-devel@alsa-project.org/message/BE4NG5O64V6VFY7RRBQ2ZYZ5M7ILWYDM/>
List-Archive: 
 <https://mailman.alsa-project.org/hyperkitty/list/alsa-devel@alsa-project.org/>
List-Help: <mailto:alsa-devel-request@alsa-project.org?subject=help>
List-Owner: <mailto:alsa-devel-owner@alsa-project.org>
List-Post: <mailto:alsa-devel@alsa-project.org>
List-Subscribe: <mailto:alsa-devel-join@alsa-project.org>
List-Unsubscribe: <mailto:alsa-devel-leave@alsa-project.org>

On Fri, 05 May 2023 18:55:12 +0200,
Srinivas Kandagatla wrote:
> 
> On Qualcomm SoC which has multiple Display Port controllers, using
> snd_pcm_add_chmap_ctls() to add chmap controls from every ASoC hdmi codec
> instance for a give card fails while adding second instance as the control
> with same name "Playback Channel Map" already exists from the first instance.
> 
> Fix this by adding a new api wrapper to pass ASoC component name prefix to
> avoid such duplicate control naming.

It implies that you have conflicting PCM objects with the same PCM
device number from the same card.  How can it be?


Takashi
